Program BiSolution
Implicit None
DOUBLE PRECISION :: A, B, M, F,ERROR,TOL
Integer :: I=0

	A=-1 !INITIAL GUESSES AND INITIALIZING INTERVAL [A,B]
	B=4
	TOL = 1.0E-10
	PRINT*,"INITIAL [A,B]","[",A,",",B,"]"
		DO !FOR 14 ITERATIONS
		M= A + (B-A)/2.0
		IF( F(M) .LT.0.0) THEN !IF FUNCTION VAL IS NEGATIVE
			A = M !ASSIGN MID POINT TO A
		ELSE 
			B = M !ASSIGN MID POINT TO B IF F(M) > 0
		END IF
I = I +1
ERROR = ABS(B-A)
PRINT*,"A:",A,"B:",B,"M:",M
		IF(ERROR.LT.TOL) THEN
			PRINT*,"ERROR",ERROR
			PRINT*,"Iterations",I
			STOP;
			END IF
END DO

PRINT*,"ERROR:",ERROR
End Program BiSolution

DOUBLE PRECISION FUNCTION F(G)
DOUBLE PRECISION G 
F = G**3 - 25
RETURN
END
